"""Live Grok bot roster lanes for the AI hub board."""

from __future__ import annotations

from typing import Any

# Synced to complaint-cases/ROSTER_BOARD.md + ROSTER.md (Phase 1 live board).
# Shot-callers: Joseph + Ziggy only. Updated: 2026-09-07.
ROSTER: list[dict[str, Any]] = [
    {
        "pod": 'Command',
        "lane": 'intake',
        "bot": 'Ziggy',
        "role": 'complaint/case collector + monitor surface',
        "agent_id": '4f908f2c-747c-4b08-9f2f-e4e6c0df0f06',
        "id_pattern": 'CASE-YYYYMMDD-NNN',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Command',
        "lane": 'balance',
        "bot": 'Gyro',
        "role": 'roster balancer under Ziggy',
        "agent_id": '6935de55-cb84-49e6-87fb-e27b5ba63466',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Command',
        "lane": 'pa',
        "bot": 'Diane Secretary And Asstiant',
        "role": 'secretary/PA — calendar, inbox, scheduling, notes',
        "agent_id": 'f6423d30-c08a-4fee-a1b8-73be7abbf2b4',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Command',
        "lane": 'time',
        "bot": 'Mod Modsklock Time Keeper Bot',
        "role": 'reminders, schedules, timers, digests',
        "agent_id": 'c2843bed-040b-4457-af7a-26003b53931e',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Command',
        "lane": 'lists',
        "bot": 'A List A Lister Angel',
        "role": 'A-lists, priorities, people/leads/projects lists',
        "agent_id": 'b05f9693-de80-4662-9a8d-a2f820971838',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Command',
        "lane": 'notes',
        "bot": 'Note Taken Nathan',
        "role": 'roster notes + security-important notes',
        "agent_id": '458c7041-86df-4f39-89b4-48ab993ddc03',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Security',
        "lane": 'threat',
        "bot": 'White Rook',
        "role": 'malware/threat/scam guard (8:00 watch)',
        "agent_id": 'da12d79b-731f-4108-8501-50fb75254e9d',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Security',
        "lane": 'guardian',
        "bot": 'Orange Ninja',
        "role": 'silent guardian',
        "agent_id": '503ca0bd-34b3-4699-aa23-977a9c3211f0',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Security',
        "lane": 'research',
        "bot": 'Private Eye X',
        "role": '9:30 dig owner',
        "agent_id": '661d987c-bf99-4684-ae1b-2e84e923168a',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Security',
        "lane": 'defense',
        "bot": 'Red Dragon Samurai Knight',
        "role": 'offense-for-defense',
        "agent_id": '51ec8625-6e74-4eb8-b1ea-7690ddd4fd24',
        "authorization": 'Joseph / Ziggy authorize',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Security',
        "lane": 'firewall',
        "bot": 'Firefly Fire 4th Wall Builder',
        "role": 'firewalls / perimeter / hardening',
        "agent_id": '7772accb-f62d-440c-9aa8-eee76694b4f2',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Security',
        "lane": 'privacy',
        "bot": 'Robert Mathis Privacy',
        "role": 'privacy/compliance wording and account hygiene language',
        "agent_id": '6b580806-94d9-4bcc-bf8b-c16489b47dcf',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'ELM Build',
        "lane": 'architecture',
        "bot": 'Archy The Architect Right Handbot',
        "role": 'architecture right-hand (cloud/infra → code/docs → GitHub/ELM)',
        "agent_id": 'e6e8cc50-63ee-461e-b2a6-2a8da2030eca',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'ELM Build',
        "lane": 'coding',
        "bot": 'Charles Code Master',
        "role": 'coding lead — any language / best stack',
        "agent_id": '15c77164-c757-41d9-be2c-a01e29d8a815',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'ELM Build',
        "lane": 'product',
        "bot": 'Devon The Developer',
        "role": 'product & software architect/developer',
        "agent_id": 'c5d918f5-965f-48a7-a834-cc45ddd8248c',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'ELM Build',
        "lane": 'software',
        "bot": 'Miss Software',
        "role": 'software craft/QA/polish + build/ship/debug/PR',
        "agent_id": 'c92c7f49-068c-4b47-818b-f07ea7bfa583',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'ELM Build',
        "lane": 'repo-repair',
        "bot": 'Crash Repo Repair',
        "role": 'repo repair/fix/scan/amend/optimize',
        "agent_id": 'd9234e7a-b18d-4884-8c78-a963ae0d55df',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'ELM Build',
        "lane": 'design',
        "bot": 'Dante The Designer',
        "role": 'design & IT architecture — apps, websites, cloud, blockchain, quantum, Matrix, IT',
        "agent_id": '6a2b628c-19a3-4f86-9f0e-b026ac031c30',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'ELM Build',
        "lane": 'qa',
        "bot": 'Dwight Freeney QA Breaker',
        "role": 'QA — break/verify builds',
        "agent_id": '397096c7-c5a0-4a80-b071-71bbc472bfe4',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'ELM Build',
        "lane": 'ai-tools',
        "bot": 'Tony Tool Bot',
        "role": 'AI tools — create/design/build/use/manage',
        "agent_id": 'e7de2b9b-ffce-4130-8c4c-5d530732f335',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'ELM Build',
        "lane": 'algorithms',
        "bot": 'The All Spark Of Algorithms',
        "role": 'algorithms — manage/create/design/develop',
        "agent_id": 'e78b28a0-d184-48b7-bb0d-06647ccfe269',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Vault / Files',
        "lane": 'vault',
        "bot": 'Hope',
        "role": 'vault / ELM tips / Grok ingest',
        "agent_id": '0667e0da-7d98-46ec-bac5-f9c83229060c',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Vault / Files',
        "lane": 'files',
        "bot": 'Fast File Manger Freddie',
        "role": 'file manage/organize/locate/retrieve/place',
        "agent_id": '08972a90-4660-454c-9aca-cd625beb1078',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Vault / Files',
        "lane": 'archive',
        "bot": 'Johnny Unitas Vault Archivist',
        "role": 'backup/vault archivist — ELM + case disaster copies',
        "agent_id": 'c46088a2-4554-4081-ac1a-4bbea4b62a38',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Vault / Files',
        "lane": 'artifacts',
        "bot": 'Indiana Jones Artifact Professor',
        "role": 'artifact IT/data from genuine artifacts',
        "agent_id": 'be8e6d6b-fe77-4c44-924a-d168207df63c',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Vault / Files',
        "lane": 'data',
        "bot": 'Edgerrin James Data Warehouse',
        "role": 'data/DB — schemas, exports, warehouses',
        "agent_id": '019dc0c3-9e55-4811-9870-e8f0991c4b5a',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Comms / Packs',
        "lane": 'mail',
        "bot": 'Marvin Harrison Mail Queue',
        "role": 'mail triage — inbox sort, support drafts, complaint correspondence',
        "agent_id": 'be7080e6-7da7-42ab-a0d8-889fec520ef6',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Comms / Packs',
        "lane": 'writing',
        "bot": 'Sudo JoJo Writing Bot',
        "role": 'writing — work, correspondence, fiction/nonfiction',
        "agent_id": 'fec134ef-6840-41c3-a9c8-45fcd1ea8107',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Comms / Packs',
        "lane": 'legal',
        "bot": 'Joe Cool.Snoopy The Legal Begal',
        "role": 'legal research, contracts/docs, letters',
        "agent_id": 'bdd5f1aa-313f-4c34-9e32-0104bae93227',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Comms / Packs',
        "lane": 'packs',
        "bot": 'Reggie Wayne Pack Publisher',
        "role": 'PDF/ZIP packs, watermarks, filing bundles',
        "agent_id": '907abdce-1340-4b3e-a783-4884cce76676',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Comms / Packs',
        "lane": 'social',
        "bot": 'So Cal Gal Bot',
        "role": 'social media — presence, marketing, influencing',
        "agent_id": 'b4f45fdf-07ac-431a-866a-88feae072074',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Comms / Packs',
        "lane": 'interpret',
        "bot": 'Rose Comprehensive Human And Other Forms Of Life Interpretor Bot',
        "role": 'interpretation across humans/species/AI/code/docs',
        "agent_id": 'b3f8cae9-164b-45e0-932b-7b2df4e44f2d',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Comms / Packs',
        "lane": 'translate',
        "bot": 'Andrew Luck Translator',
        "role": 'human-language translation and localization',
        "agent_id": '3826c910-5145-4862-b4fb-ef242994e626',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Money / Biz',
        "lane": 'books',
        "bot": 'Peyton Manning The Books',
        "role": 'household money — budgets, bills, bookkeeping, tax-prep support',
        "agent_id": '2a256961-c33c-431b-b812-9cadc05deaf3',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Money / Biz',
        "lane": 'stock-runner',
        "bot": 'Top Stock Flash Rudy The Runner',
        "role": 'stock market runner — movers, watchlist, news',
        "agent_id": 'cfe682ff-7f97-46d0-a59a-0aaf2d62148c',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Money / Biz',
        "lane": 'stock-picker',
        "bot": 'Top Stock Philip The picker',
        "role": 'stock picker — picks, watchlist, setups',
        "agent_id": 'f39bd73f-8f8e-43c4-aa6a-77b6ceb6079b',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Money / Biz',
        "lane": 'stock-buyer',
        "bot": 'Top Stock Bully Bear The Buyer',
        "role": 'stock buyer — decisions, execution, buy watchlist',
        "agent_id": 'a9653961-c5af-4192-b6ab-ee24de353da6',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Money / Biz',
        "lane": 'blockchain',
        "bot": 'Bad Ass Billy Gold Block Chain',
        "role": 'crypto / blockchain research, tracking, on-chain build',
        "agent_id": '690575fd-714a-43c7-bb4d-009af3ac04a9',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Money / Biz',
        "lane": 'investments',
        "bot": 'Kelser Professional',
        "role": 'Kelser & Suns Investments management',
        "agent_id": '2dd89117-5b64-4700-b4e0-adbb8baffee3',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Money / Biz',
        "lane": 'real-estate',
        "bot": 'Rudolph Real Estate Evaluation And Realitor',
        "role": 'investment property scout for Kelser & Suns',
        "agent_id": '2652eb10-3f16-4353-890e-98dc0d7f8294',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Money / Biz',
        "lane": 'crm',
        "bot": 'Adam Vinatieri CRM',
        "role": 'CRM / client book — leads and contacts',
        "agent_id": 'a3257e65-ac52-494d-952e-18770f900a7d',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Money / Biz',
        "lane": 'grants',
        "bot": 'Dallas Clark Grants Scout',
        "role": 'grants/funding scout',
        "agent_id": '4bdd80eb-9b9f-4925-aedc-65b5438e4740',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Money / Biz',
        "lane": 'jobs',
        "bot": 'Junior The Job Hunter',
        "role": 'job hunter — paying web work; bot↔job matches',
        "agent_id": '7fa7ec59-b476-4725-8e2e-356a06f32490',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Ops Life',
        "lane": 'home',
        "bot": 'Quenton Nelson Home Ops',
        "role": 'Kokomo home — house, utilities, maintenance',
        "agent_id": 'e9a89df9-e060-45bd-969f-bc4d62926ecb',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Ops Life',
        "lane": 'shopper',
        "bot": 'T.Y. Hilton Shopper Scout',
        "role": 'procurement — deals, parts, supplies',
        "agent_id": 'cb5fd128-66ba-44ee-b743-08e3d511cfa0',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Ops Life',
        "lane": 'transport',
        "bot": 'Rerun Tracker Routing And Routes Bot',
        "role": 'transportation routing & orders',
        "agent_id": '1121c461-109b-4523-8569-6b5a91d91999',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Ops Life',
        "lane": 'tech-support',
        "bot": 'TK Technical Support',
        "role": 'tech support for Joseph, Ziggy, and roster',
        "agent_id": '1f6403b4-5a54-4c50-9e1d-940b9d63251f',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Ops Life',
        "lane": 'cleanup',
        "bot": 'Howie The Mean Green Clean Bot.',
        "role": 'cleanup — optimize/organize devices & files',
        "agent_id": '62569133-4c3e-4893-9e7b-959d73ff562e',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'apps',
        "bot": 'Apache Applications Bot',
        "role": 'mechanical, robotics, industrial, agriculture apps',
        "agent_id": 'eedb3fa0-d7e5-4b7e-8084-82a736a7f15f',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'cad',
        "bot": 'Jonathan Taylor CAD Print',
        "role": 'CAD / 3D print models and print files',
        "agent_id": '691ce7b8-d1bc-4554-ad91-78610f9dc9f9',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'training',
        "bot": 'Coach The A.I And Robot And Optimus Training Bot',
        "role": 'AI/robot/Optimus training coach',
        "agent_id": '5ade5587-4543-4b3c-b029-a64362a709f0',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'quantum',
        "bot": 'Quincy The Quantum Professional',
        "role": 'quantum computing research & adapt',
        "agent_id": '5d629698-30ab-4205-bf41-a11a34007e50',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'math',
        "bot": 'Starven Marvin Mathematician',
        "role": 'math lead — algebra, geometry, trig, calcs',
        "agent_id": '83d33ac3-b286-435c-8ac5-6027c249528e',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'logarithms',
        "bot": 'Logan Logarthem Bot',
        "role": 'logarithms — math, data, research, reasoning',
        "agent_id": 'fa1b8534-bdab-47b1-8080-95f0f832863f',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'science',
        "bot": 'Mr.Wizard Science Bot',
        "role": 'research & experimental science',
        "agent_id": '8808abee-89d4-40b4-958f-e30f31cf40b9',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'audio',
        "bot": 'Rockso Rock N Roll Bot',
        "role": 'music / audio lead',
        "agent_id": '5bcff096-839e-4b96-bd0d-de582bec6426',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'media',
        "bot": 'Vid Cambot',
        "role": 'media capture/assist',
        "agent_id": '444234c7-7915-4b3d-9ee8-f830ece8251a',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'news',
        "bot": 'Pat McAfee News Brief',
        "role": 'news digests — public/threat/market headlines',
        "agent_id": '34386fb2-726a-457f-9603-e665120ab436',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'insurance',
        "bot": 'Eric Dickerson Insurance',
        "role": 'insurance/claims — policies and claim paperwork',
        "agent_id": '74eefa2b-ae29-4dc5-b580-1a14e6691c97',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'matrix',
        "bot": 'Neo Matrix Guy',
        "role": 'Matrix-connected research/ops/security/coding',
        "agent_id": 'e789a5c0-a276-43c2-9b29-bfad24f7a04f',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'location',
        "bot": 'Loki The Location Locator',
        "role": 'locate/verify people, places, contacts, properties',
        "agent_id": '25b6b31e-d3e2-4fb7-b98a-3ba865f9ed04',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'systems',
        "bot": 'Jack The Bot Of All Trades And Services',
        "role": 'systems for human/AI/device/robotic/Optimus',
        "agent_id": '429cd5f8-f0c3-4889-b47d-c347b696b686',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'cloud-web',
        "bot": 'Web Master Cloud Sentenal',
        "role": 'cloud / websites / connected servers',
        "agent_id": '4ba18fb4-10de-4aa9-8371-c431ef760078',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'logic',
        "bot": 'Lee Roy Logic Bot',
        "role": 'logic/reasoning/decision support',
        "agent_id": 'e6b4ba96-2a22-480d-a952-193cb09bfdad',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'reasoning',
        "bot": 'Ronnie Reasoning Bot',
        "role": 'situational reasoning; help bots connect to Ziggy',
        "agent_id": 'ee268654-9827-4e15-a0d3-8ee10e943d32',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'analysis',
        "bot": 'Anna The Analizer',
        "role": 'analyze roster data/research/code/systems/ops',
        "agent_id": 'cfae666a-5167-414d-aa7b-4fb0d903b940',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'examiner',
        "bot": 'Elmer The Examiner',
        "role": 'examine docs, claims, systems, people, cases',
        "agent_id": 'd2b7ce73-c3f4-42c9-a003-56a095a4a23c',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Domain',
        "lane": 'evaluator',
        "bot": 'EL Evo The Evaluator',
        "role": 'evaluate roster activity; help bots evaluate tasks',
        "agent_id": '2fb725e1-b432-4188-ab2b-0b13086c046a',
        "status": 'OPERATIONAL',
    },
    {
        "pod": 'Reserve',
        "lane": 'reserve',
        "bot": 'New Bot',
        "role": 'placeholder TBD — do not invent capabilities',
        "status": 'PLACEHOLDER',
    },
]


def roster_lanes() -> list[dict[str, Any]]:
    return [dict(r) for r in ROSTER]


def roster_by_pod() -> dict[str, list[dict[str, Any]]]:
    out: dict[str, list[dict[str, Any]]] = {}
    for row in roster_lanes():
        out.setdefault(str(row.get("pod", "Unassigned")), []).append(row)
    return out

